### ISSUE TITLE
csg operation error

### ISSUE THREAD

**Issue by czc98** [gkjohnson/three-bvh-csg#204] opened 2024-03-28 03:24 UTC
`const brush1 = new Brush(geometry1);
brush1.updateMatrixWorld();
const brush2 = new Brush(geometry2);
brush2.updateMatrixWorld();
const evaluator = new Evaluator();
const result = evaluator.evaluate(brush1, brush2, ADDITION);
console.log(result);`

![image](https://github.com/gkjohnson/three-bvh-csg/assets/63877428/ef27990c-e032-4647-b8d4-3a389677de13)
TypeError: Cannot read properties of undefined (reading 'array')
It is meaning that the brush geometry not be two-manifold?

**Comment by gkjohnson** [comment] 2024-03-28 03:45
Please provide a working example of the problem. There's no way to say what the issue is with the information you provided.

**Comment by czc98** [comment] 2024-03-28 06:49
[stl_models.zip](https://github.com/gkjohnson/three-bvh-csg/files/14785055/stl_models.zip)
I just do simple operation of this two stl meshes, but i not work.
if the reason that error is the model not require the two-manifold?

**Comment by gkjohnson** [comment] 2024-03-28 07:25
> stl_models.zip

This is not a live example. I'm sorry but I cannot take the time to try to recreate your issue. Please provide a useable example with something like [jsfiddle](https://jsfiddle.net/) or [codesandbox](https://codesandbox.io/) that shows the error.

> if the reason that error is the model not require the two-manifold?

There is no detection for two manifold geometry in the project. It is the applications responsibility to enforce this.

**Comment by gkjohnson** [comment] 2024-03-28 23:27
Closing until we have a reproduction case.

**Closed by gkjohnson** 2024-03-28 23:27 UTC
