### ISSUE TITLE
Extra edges after complex subtraction

### ISSUE THREAD

**Issue by codand** [gkjohnson/three-bvh-csg#181] opened 2023-11-23 00:03 UTC
Subtracting a box (or any shape) from a 3DBenchy (popular 3D print) produces a geometry with several incorrect edges contained in the subtraction area. These are only visible when rendering the result wireframe.

Repro: Open [this codesandbox link ](https://codesandbox.io/p/sandbox/three-bvh-csg-example-s3n7wt?file=%2Fsrc%2Fsimple.js%3A272%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpaabls80007356nkyl6y09n%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpaabls80003356nizvc4xv2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpaabls80004356nxhypiu5r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpaabls80006356nwbu8a022%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B43.03857481502765%252C56.96142518497235%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpaabls80003356nizvc4xv2%2522%253A%257B%2522id%2522%253A%2522clpaabls80003356nizvc4xv2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpab6j5m0003356nkso1qdg0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A272%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A272%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fsimple.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clpabb4sr0003356noko8qbqd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2%252C%2522startColumn%2522%253A34%252C%2522endLineNumber%2522%253A2%252C%2522endColumn%2522%253A34%257D%255D%252C%2522filepath%2522%253A%2522%252Fsandbox.config.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpab6j5m0003356nkso1qdg0%2522%257D%252C%2522clpaabls80006356nwbu8a022%2522%253A%257B%2522id%2522%253A%2522clpaabls80006356nwbu8a022%2522%252C%2522activeTabId%2522%253A%2522clpaagct200cf356n2fg2lhze%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clpaagct200cf356n2fg2lhze%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%252C%2522clpaabls80004356nxhypiu5r%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpaabls80004356nxhypiu5r%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)  (adapted from the Simple CSG example) and set brush 1's shape to "mesh".

Additional info:

isWaterTight reports true for this mesh,

Blender's 3D print checker also reports zero non-manifold edges.
![image](https://github.com/gkjohnson/three-bvh-csg/assets/2474928/fdd6cca9-2a7c-4f7a-b4e6-4db8d2cb00d3)
![image](https://github.com/gkjohnson/three-bvh-csg/assets/2474928/821f8de7-b816-43df-9a37-4dd644bc6abf)
![image](https://github.com/gkjohnson/three-bvh-csg/assets/2474928/cdd71728-824e-4b51-b58e-39dce657b591)

Hope this report might help figure out some edge cases.

**Comment by gkjohnson** [comment] 2023-11-23 02:27
Interesting - I'm also seeing that "intersectionEdges" is reporting some odd extraneous edges:

<img width="669" alt="image" src="https://github.com/gkjohnson/three-bvh-csg/assets/734200/0b915599-96df-4ffe-bccd-298c423aa2cd">

Can you please produce a simpler example that just includes the two geometries and the clipping operaiton?

**Comment by codand** [comment] 2023-11-23 03:46
> Can you please produce a simpler example that just includes the two geometries and the clipping operation and the wireframe?

Sure. [here's a stripped down version](https://codesandbox.io/p/sandbox/three-bvh-csg-example-simple-forked-938d2t?file=%2Fsrc%2Fsimple.js%3A171%2C20&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpaabls80007356nkyl6y09n%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpaabls80003356nizvc4xv2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpaabls80004356nxhypiu5r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpaabls80006356nwbu8a022%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B51.63565835787659%252C48.36434164212341%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpaabls80003356nizvc4xv2%2522%253A%257B%2522id%2522%253A%2522clpaabls80003356nizvc4xv2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpabb4sr0003356noko8qbqd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2%252C%2522startColumn%2522%253A34%252C%2522endLineNumber%2522%253A2%252C%2522endColumn%2522%253A34%257D%255D%252C%2522filepath%2522%253A%2522%252Fsandbox.config.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clpamz32u0003356nd056st3g%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A171%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A171%252C%2522endColumn%2522%253A20%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fsimple.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpamz32u0003356nd056st3g%2522%257D%252C%2522clpaabls80006356nwbu8a022%2522%253A%257B%2522id%2522%253A%2522clpaabls80006356nwbu8a022%2522%252C%2522activeTabId%2522%253A%2522clpaagct200cf356n2fg2lhze%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clpaagct200cf356n2fg2lhze%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%252C%2522clpaabls80004356nxhypiu5r%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpaabls80004356nxhypiu5r%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

**Comment by gkjohnson** [comment] 2023-12-05 11:20
I fixed #183 in v0.0.15 which _seemed_ to be related but it does not seem to have fixed this issue. Are you seeing this same kind of issue with any simpler models? Ideally generated models from the three.js primitives?

**Comment by codand** [comment] 2023-12-05 17:42
I've not yet seen it happen from a single subtraction between two threejs primitives, but I have seen it happen after multiple consecutive subtractions. I'll see if I can produce a simpler example on the latest update this week. Thank you for investigating!

**Comment by gkjohnson** [comment] 2024-01-02 13:42
It looks this this is happening as part of the "full triangle" accumulation step - ie the step where unclipped triangles are appended to the result.

<img width="400" alt="image" src="https://github.com/gkjohnson/three-bvh-csg/assets/734200/a9ccf8df-655f-4ea2-9ea7-eb1f1d3a8b4a">

These edges look like they intersect the the clip volume, though, so it's odd that they're marked as "unclipped" - though the intersection function likely reasonably assumes that the triangles are not completely degenerate:

<img width="400" alt="image" src="https://github.com/gkjohnson/three-bvh-csg/assets/734200/3ed83c53-e83e-4927-9eaa-a5b9931549d6">

They're gone if we filter triangles with area === 0 when building the result geometry:

<img width="520" alt="image" src="https://github.com/gkjohnson/three-bvh-csg/assets/734200/9cf0dbcf-aa6a-4fb9-9d24-8e0df57a9816">

These degenerate triangles are in the original model, as well - 563 of them. I guess these will have to be filtered out during the clip process. I'll just have to think abut the right place to do it.

**Comment by gkjohnson** [comment] 2024-01-02 15:11
#193 should fix it:

<img width="500" alt="image" src="https://github.com/gkjohnson/three-bvh-csg/assets/734200/88254135-076e-4899-b9bf-23b4da737009">

<img width="500" alt="image" src="https://github.com/gkjohnson/three-bvh-csg/assets/734200/74fd89a4-e682-406f-ad2a-7f55e34ca6db">

**Comment by gkjohnson** [comment] 2024-01-02 15:13
I still want to check out the "intersection edges" issue listed above, though.

**Comment by gkjohnson** [comment] 2024-01-03 02:52
Looks like the eges issue can't be easily reproduced at the moment - we can track it down when it arrises another time:

<img width="733" alt="image" src="https://github.com/gkjohnson/three-bvh-csg/assets/734200/1638a741-62cd-445d-9745-2b94d1e86dd3">

**Closed** 2024-01-03 02:52 UTC
Labels: bug
